version: 2

project_name: peselbrute

before:
  hooks:
    - go mod tidy

builds:
  - id: peselbrute
    binary: peselbrute
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - mips64le
      - ppc64le
      - riscv64
      - s390x
    goarm:
      - "6"
      - "7"
    ignore:
      # darwin only supports amd64 and arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: mips64le
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: riscv64
      - goos: darwin
        goarch: s390x
      # windows does not support arm/mips/ppc/riscv/s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: mips64le
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: riscv64
      - goos: windows
        goarch: s390x
      # freebsd does not support mips/ppc/riscv/s390x
      - goos: freebsd
        goarch: mips64le
      - goos: freebsd
        goarch: ppc64le
      - goos: freebsd
        goarch: riscv64
      - goos: freebsd
        goarch: s390x
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: peselbrute
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
